export const STORE_KEY = '@@preview'
export const REGISTER_PREVIEW_FRAME = `${STORE_KEY}/REGISTER_PREVIEW_FRAME`
export const UPDATE_NEXT_FRAME_URL = `${STORE_KEY}/UPDATE_NEXT_FRAME_URL`
export const CHANGE_PAGE = `${STORE_KEY}/CHANGE_PAGE`
